### PR TITLE
Enhance IPackageController.before_search options

### PR DESCRIPTION
**Pull request by curtisyallop**
Added an option to let IPackageController.before_search alter the
include_private part of the solr dataset search filter.

### CODE REVIEW

**Comment by neilmayhew** [comment]
The logic looks good to me. I just have a problem with the key name. `private_extra_clause` doesn't fit well with the other keys that do a similar thing (`include_private` and `include_drafts`) and doesn't communicate well about what it does. I think `include_other` might be better, especially since it's combined using an `OR` and therefore widens the search. It might also be good to use `ext_` in front of the key name, to show that it comes from an extension (if I've understood the meaning of `ext_` correctly) but drop the prefix for the variable name, ie keep it as `include_other` in the code. (If using `ext_`, the first `pop()` can be omitted.)

**Comment by curtisyallop** [comment]
"ext_" stands for extra, not extension. As in the extras fields. Non-core dataset fields added to and stored in package_extras, not as fields of table package. ckan does not prefix "ext_" to include_private/include_drafts so we should probably not prefix it for our new one. If we do not pop it, ext_* fields will be saved and that is not what we want. If you look above, it actually pops all the ext_* fields already then saves them later as extras. But after popping them, it calls the before_search listening extensions, so technically, we could set ext_ fields and it would not be saved. But that would not be very clean.

include_private and include_drafts are booleans. It is a bit confusing to name it "include_other" and then assign it a solr string value when the other 2 are booleans. Also, note that it only applies when the user is logged in and include_private is true.

How about "include_other_clause" or "include_other_condition" or "include_private_extra"?

**Comment by neilmayhew** [comment]
Thanks for clarifying. I agree that using `ext_` isn't appropriate. Also, I hadn't thought about the other two `include_` variables being booleans. Of the alternative names you suggest, I like `include_other_condition` the best, and `include_other_clause` next.

Using `private` in the name is too similar to the metadata field for being private or not, and although this is still related to whether things are visible, it's not (as far as this code is concerned) about the `private` field itself.

**Comment by curtisyallop** [comment]
ok, include_other_condition then.

**Comment by neilmayhew** [comment]
:+1:

**Pull request merged**
